chore: add GHA workflow to build the container
getsentry/uptime-checker pull request #158
Opened 2024-08-30 09:50 UTC by TheDevMinerTV

Fixes #157

2024-09-09 05:18 UTC, aldy505 commented
cc @evanpurkhiser, please?

2024-09-09 23:22 UTC, evanpurkhiser commented on .github/workflows/release.yml
> +    name: "Release a new Relay version"
This should be fixed

2024-09-09 23:23 UTC, evanpurkhiser commented
Going to forward this over to our open source release management team. Thanks!

2024-09-09 23:56 UTC, hubertdeng123 commented
Looks like uptime-checker is in EA right now. Let's hold off on this for now until we can get this integrated into self-hosted

2024-09-10 03:28 UTC, aldy505 commented
> Looks like uptime-checker is in EA right now. Let's hold off on this for now until we can get this integrated into self-hosted

@hubertdeng123 fun fact: I did get this integrated on my instance. https://github.com/getsentry/self-hosted/issues/3304

2025-02-13 01:29 UTC, aldy505 commented
@TheDevMinerTV We would need to revisit this. Should refer to the symbolicator's way of building the Docker image and pushing to both GHCR and DockerHub. See this: https://github.com/getsentry/symbolicator/blob/master/.github/workflows/image.yml

It would be nice if we can build to arm64 too.

2025-03-01 05:22 UTC, aldy505 reviewed
cc @wedamija @evanpurkhiser

2025-03-01 05:22 UTC, aldy505 commented on .craft.yml
> +    source: ghcr.io/getsentry/uptime-checker
Different than other repos, I guess using GHCR as the default source is a better thing to do since it is guaranteed open source and guaranteed not to be tampered with.

2025-03-01 05:22 UTC, aldy505 commented on .github/workflows/build-image.yaml
> +    name: Publish uptime-checker to DockerHub
After publishing to GHCR, you could remove the GCR build and just copy the GHCR image to GCR like what Relay did here https://github.com/getsentry/relay/blob/ac330795fdb9d00ce158f200c380b7b364100bd5/.github/workflows/ci.yml#L403-L408

2025-03-01 05:22 UTC, aldy505 commented on Dockerfile
> +FROM rust:1.80-alpine3.20 AS builder
A nitpick, using lowercased "as" emit a warning on Docker.

2025-03-06 13:24 UTC, aldy505 commented
@wedamija @evanpurkhiser Any chance to take a look at this one?

2025-03-13 12:13 UTC, JoshFerge approved these changes

2025-03-14 01:48 UTC, aldy505 commented
Any chance this will get merged before 15 March?

2025-03-24 06:44 UTC, aldy505 commented
@wedamija @evanpurkhiser Anything?

2025-03-26 16:22 UTC, BYK requested changes
Rejecting to split the GHCR builds from the actual release set up.

2025-03-26 16:22 UTC, BYK commented on .craft.yml
> +    source: ghcr.io/getsentry/uptime-checker
I think this should be done in 2 separate steps as currently we build on Google Cloud and the GitHub context you block on (defined above) is the Google Cloud Build status anyway. Let's go with that image first and then do the switch over across all repos.

```suggestion
    source: us-central1-docker.pkg.dev/sentryio/uptime-checker/image
```

2025-03-26 16:22 UTC, BYK commented on .github/workflows/build-image.yaml
> +    name: Publish uptime-checker to DockerHub
All this should be in a separate patch

2025-03-26 16:22 UTC, BYK commented on .github/workflows/release.yml
> +    # We also want it to be 1 hour before the on-prem release
```suggestion
    # We also want it to be 1 hour before the self-hosted release
```

2025-03-27 07:19 UTC, aldy505 commented on .craft.yml
> +    source: ghcr.io/getsentry/uptime-checker
@BYK How can we guarantee if the image on the GCR is being successfully built?

2025-03-27 07:19 UTC, aldy505 commented on .github/workflows/build-image.yaml
> +    name: Publish uptime-checker to DockerHub
@BYK By "all this", did you mean removing the GCR build?

2025-03-27 13:48 UTC, BYK commented on .craft.yml
> +    source: ghcr.io/getsentry/uptime-checker
@aldy505 that's what Craft does with the status check? GitHub status check would fail if that Google Cloud build fails which then would be picked up by Craft, cancelling the publishing?

2025-03-27 13:48 UTC, BYK commented on .github/workflows/build-image.yaml
> +    name: Publish uptime-checker to DockerHub
Yup, this entire job.

2025-03-27 14:13 UTC, aldy505 commented on .craft.yml
> +    source: ghcr.io/getsentry/uptime-checker
Ah! TIL.

2025-03-28 03:00 UTC, aldy505 commented
@BYK Can you re-review today?

2025-03-28 10:52 UTC, BYK commented on .github/workflows/build-image.yaml
> +              --push \
Less error prone: (see https://yaml-multiline.info/ for more info)
```suggestion
        run: >-
          docker buildx build
              --platform linux/arm64,linux/amd64
               $( [[ "${GITHUB_REF}" == "refs/heads/main" ]] && printf %s "--tag ${NIGHTLY_IMAGE}" )
              --tag "${VERSIONED_IMAGE}"
              --file Dockerfile
              --push
```

2025-03-28 13:36 UTC, aldy505 commented on .github/workflows/build-image.yaml
> +    name: Publish uptime-checker to DockerHub
I don't see why not now? If we rely on the GCR build, we would need the `until ...` command that would take up a long time for the GHA to finish.

2025-03-29 05:28 UTC, aldy505 commented on .github/workflows/build-image.yaml
> +    if: ${{ !github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]' }}
We could simply do
```yml
if: github.repository_owner == 'getsentry'
```

2025-03-31 10:28 UTC, BYK approved these changes
Not happy about the double building and need an answer for the different `source` parts in the Craft config file. Otherwise looks good, thanks a lot for getting through with this!

2025-03-31 10:28 UTC, BYK commented on .github/workflows/build-image.yaml
> +    if: ${{ !github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]' }}
Not sure if that works with dependabot

2025-03-31 10:28 UTC, BYK commented on .github/workflows/build-image.yaml
> +    if: ${{ !github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]' }}
Yeah it doesn't and we had to do something contrived over at Spotlight too: https://github.com/getsentry/spotlight/pull/702/files

2025-03-31 10:28 UTC, BYK commented on .craft.yml
> +    source: ghcr.io/getsentry/uptime-checker
I think these sources should match?

2025-03-31 10:28 UTC, BYK commented on .github/workflows/build-image.yaml
> +          docker buildx build
I really do not like us double building this image (once in Google Cloud and once in GHA). Looks like a big waste of resources. @asottile-sentry do you know if we have any plans to address this?

2025-04-14 02:32 UTC, aldy505 commented
Any updates? It's been months now.

2025-04-22 13:57 UTC, aldy505 commented
Anything? @evanpurkhiser @BYK @hubertdeng123

2025-04-22 20:05 UTC, mdtro commented on .github/workflows/build-image.yaml
Let's pin the GitHub Actions to their respective SHAs instead of just the `@v1`, `@v3`, etc tags.

2025-04-22 20:06 UTC, mdtro commented on .github/workflows/release.yml
Let's pin the GitHub Actions to their respective SHAs instead of just the `@v1`, `@v3`, etc tags.

2025-04-22 20:08 UTC, mdtro commented on .github/workflows/build-image.yaml
> +jobs:
Set appropriate permissions for the jobs within the action. You can do this for all jobs, or within each specific job entry.

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token

2025-04-22 20:10 UTC, evanpurkhiser commented
Gonna go ahead and merge this and we can just iterate, sorry for blocking you forever on this @aldy505

2025-04-22 20:10 UTC, merged